config/routes.rb
Challengesplatform::Application.routes.draw do
  match '/challenges/page/:page' => "challenges#index"
  match '/challenges/:filter/(page/:page)' => "challenges#index", :constraints => { :filter => /upcoming|running|past|enrolled|supervising/ }

  resources :challenges, :constraints => { :id => /[0-9]+/ } do
    get 'revoke', :on => :member
    get 'enroll', :on => :member
    get 'unenroll', :on => :member
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  }

  resources :users, :except => [:index, :create] do
    get 'profile', :on => :member, :to => "profile#show"
    get 'followers' => 'follow#followers'
    get 'follows' => 'follow#follows'
    resources :follow, :only => [:create, :destroy]
  end

  match "split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated? # are we authenticated?
    request.env['warden'].authenticate! # authenticate if not already
    # or even check any other condition
    request.env['warden'].user.is_admin?
  }
  get "messages/compose", :to => "messages#compose"
  post "messages/deliver", :to => "messages#deliver", :as => :message_deliver
  put "messages/update", :to => "messages#update", :as => :messages_update
  get "messages/autosuggest", :to => "messages#autosuggest"
  get "messages/markasread/:id", :to => "messages#markasread", :as => "markasread"
  
  resources :messages, :only => [:show, :destroy, :index]

  namespace :admin do
    resources :review, :only => [:decline, :approve, :edit, :index, :show, :update] do
      post 'decline', :on => :member
      post 'approve', :on => :member
      get 'edit', :on => :member
      put 'edit', :on => :member
    end

    resources :usermanagement, :only => [:index] do
      get 'index', :on => :member
    end

    resources :users, :only => [:edit, :update, :destroy, :new, :create]
  end

  resources :comment

  namespace :supervisor do
    resources :review 
  end

  get "query", :to => "search#query"
  get "search", :to => "search#index"

  get "static/index"
  get "aboutus", :to => "static#aboutus"
  get "team", :to => "static#team"
  get "createchallenge", :to => "static#createchallenge"
  get "challengeguidelines", :to => "static#challengeguidelines"
  get "universities", :to => "static#universities"
  get "companies", :to => "static#companies"
  get "termsofservice", :to => "static#termsofservice"
  get "privacy", :to => "static#privacy"
  get "press", :to => "static#press"

  get "dashboard", :to => "dashboard#index"

  root :to => 'static#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :receiver_id, :is_read, :subject, :sender_id

  searchable do
    text :subject, :boost => 3, :as => :subject_ngram
    text :sender do
       @user = User.find(sender_id)
       @user.firstname << " " << @user.lastname
    end

    string :type do
      "Message"
    end
    integer :sender_id
    integer :receiver_id
  end
  
  belongs_to :sender, :class_name => 'User'
  belongs_to :receiver, :class_name => 'User'
  
  scope :unread, where(:is_read => false)
  default_scope order('created_at DESC')

  scope :visible_for_user, lambda { |user|
    where(:receiver_id => user.id)
  }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # Allow regular users some views
  skip_filter :require_admin, :require_supervisor, :only => [:index, :show, :destroy, :compose, :deliver, :autosuggest, :markasread, :update]

  def index
    if request.xhr?
      render "index_modal", :layout => false
      
      # automatically mark messages shorter than the truncate length as read
      current_user.received_messages.unread.limit(3).each do |message|
        if message.body.length <= 150
          message.is_read = true
          message.save
        end
      end
    end
  end
  
  def show
    @message = current_user.received_messages.find(params[:id])
    @message.is_read = true
    @message.save
  end
  
  def markasread
    @message = current_user.received_messages.find(params[:id])
    @message.is_read = true
    @message.save
    redirect_to messages_path, :notice => "Message marked as read"
  end
  
  def destroy
    @message = current_user.received_messages.find(params[:id])
    @message.destroy
    
    redirect_to messages_path, :notice => "Message deleted."
  end
  
  def autosuggest
    search_param = params[:term].split(",").last.strip.downcase
    
    users = User.all.select{ |user| current_user.can_send_message_to_user? user }
    users.map!{ |user| { :value => user.id, :label => user.firstname + ' ' + user.lastname } }
    users.select!{ |user| user[:label].downcase.include? search_param}
    
    render :json => users
  end
  
  def compose
    # Only serve AJAX requests for now

    if request.xhr?
      render "compose_modal", :layout => false
    else
      render :nothing => true
    end
  end
  
  def deliver
    if params.has_key?(:grouptype) && params.has_key?(:groupid) && params.has_key?(:subject) && params.has_key?(:body)
      case params[:grouptype]
        when "challenge"
          check_challenge
        when "user"
          check_user
      end
    end
    
    unless defined? @group
      # If malformed request, redirect the user.
      redirect_to dashboard_path, alert: "You do not have the permissions required to view this page."
    else
      sendMessageToGroup(@group, current_user, params[:subject], params[:body])
      
      # Redirect the user to previous page and show a flash message!
      redirect_to :back, :notice => "Your message has been sent."
    end
  end
  
  def update
    selected_messages = current_user.received_messages.where(:id => params[:message_ids])
    if params[:commit] == "Mark selected as Read"
      selected_messages.update_all(:is_read => true)
    elsif params[:commit] == "Delete selected"
      selected_messages.delete_all
    end
    
    redirect_to messages_path
  end
  
  def check_challenge
    if Challenge.exists?(params[:groupid]) && current_user.can_send_message_to_participants?(Challenge.find(params[:groupid]))
      @group = Challenge.find(params[:groupid]).participants
    end
  end
  
  def check_user
    user_ids = params[:groupid].split(",")
    user_ids.uniq!
    user_ids.select! { |id| User.exists?(id) && current_user.can_send_message_to_user?(User.find(id))}
    unless user_ids.empty?
      @group = user_ids.map { |id| User.find(id) }
    end
  end
  
  private :check_challenge, :check_user
  
end

app/helpers/messages_helper.rb
module MessagesHelper
  
  def get_date(message)
    message.created_at.strftime("%d-%m-%Y %H:%M:%S")
  end
  
  def get_name(user)
    "#{user.firstname} #{user.lastname}"
  end
  
  def get_reply_subject(message)
    if message.subject.start_with? 'Re: '
      h(message.subject)
    else
      h('Re: ' + message.subject)
    end
  end
  
end

app/views/messages/compose_modal.html.haml
= form_tag message_deliver_path, :method => :post, :class => "form" do
  %div.modal-header
    %h2
      %i.icon-edit
      New Message
  %div.modal-body
    = hidden_field_tag(:grouptype)
    %div
      = hidden_field_tag(:groupid, nil, :placeholder => "To", :class => "span5")
    %div
      = text_field_tag(:subject, nil, :id => "subject", :placeholder => "Subject", :class => "span5")
    %div
      = text_area_tag(:body, nil, :id => "body", :class => "span5", :rows => 10)
  %div.modal-footer
    %span.pull-right
      %a.btn{:href => '#', :onClick => '$(this.parentNode.parentNode.parentNode.parentNode).modal("hide")'}
        Cancel
      %button.btn.btn-primary{:type => "submit"}
        Send

app/views/messages/index.html.haml
%h1 Inbox
- if current_user.received_messages.empty?
  %h2 You have no messages
- else
  = form_tag messages_update_path, :method => :put do
    %table#messagetable.table.table-hover
      %thead
        %tr
          %th 
            = check_box_tag "massselector"
          %th Subject
          %th 
          %th 
      %tbody
        - current_user.received_messages.each do |message|
          %tr{:class => message.is_read ? "mail-message read" : "mail-message unread"}
            %td
              = check_box_tag "message_ids[]", message.id
            %td
              = link_to message_path(message) do
                = message.subject
              %br
              = truncate(message.body, :length => 80).html_safe
              %br
              - unless message.is_read
                %span.readstatus
                  &#9679; unread
              %span.time
                %i.icon-time
                = get_date(message)
              %span.from-user
                %i.icon-user
                = link_to get_name(message.sender), profile_user_path(message.sender)
            %td
              = link_to message_path(message), :confirm => "are you sure?", :method => :delete, :title => "Delete", :alt => "Delete" do
                %i.icon-trash
            %td
              = link_to markasread_path(message), :title => "Mark as Read" do
                %i.icon-eye-open
    = submit_tag "Mark selected as Read", :class => "btn btn-info"
    = submit_tag "Delete selected", :class => "btn btn-danger"

app/views/messages/index_modal.html.haml
%div.modal-header
  %h2
    %i.icon-inbox
    Unread Messages
%div.modal-body
  - if current_user.received_messages.unread.empty?
    .message
      You have no unread messages
  - else
    - current_user.received_messages.unread.limit(3).each do |message|
      .message
        %h4
          = link_to message_path(message) do
            = message.subject
        %br
        %p= truncate(message.body, :length => 150).html_safe
        %p
          %i.icon-user
          = link_to get_name(message.sender), profile_user_path(message.sender)
          &mdash;
          %a
            = link_to "Read full &raquo;".html_safe, message_path(message)
%div.modal-footer
  %span.pull-right
    %a.btn{:href => '#', :onClick => '$(this.parentNode.parentNode.parentNode).modal("hide")'}
      Close
    %a#gotoinbox.btn.btn-primary{:href => messages_path}
      Go to Inbox

app/views/messages/mail_footer.html.haml
%div
  View
  = link_to "online", message_url(@message, :only_path => false)
%div
  Manage your notification settings
  = link_to "here", edit_user_registration_url(:only_path => false)

app/views/messages/show.html.haml
%input{:type=>"hidden", :value => "messages.#{@message.id}", :id => "page_identifier"}
= link_to "&laquo; back to Inbox".html_safe, messages_path
= image_tag Gravatar.new(@message.sender.email).image_url, :class => 'img-rounded pull-right'
%h2= @message.subject
%p
  %em
    = get_date(@message)
    &mdash; from 
    = link_to get_name(@message.sender), profile_user_path(@message.sender)
%p
  = @message.body.html_safe
%p
  = link_to "Delete", message_path(@message), :class => 'btn btn-danger', :confirm => "are you sure?", :method => :delete
  %a.btn.btn-primary{ :href => "#", :onClick => "composeMessage('user', #{@message.sender.id}, { subject: '#{get_reply_subject(@message)}'})" }
    Reply