config/routes.rb
Challengesplatform::Application.routes.draw do
  match '/challenges/page/:page' => "challenges#index"
  match '/challenges/:filter/(page/:page)' => "challenges#index", :constraints => { :filter => /upcoming|running|past|enrolled|supervising/ }

  resources :challenges, :constraints => { :id => /[0-9]+/ } do
    get 'revoke', :on => :member
    get 'enroll', :on => :member
    get 'unenroll', :on => :member
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  }

  resources :users, :except => [:index, :create] do
    get 'profile', :on => :member, :to => "profile#show"
    get 'followers' => 'follow#followers'
    get 'follows' => 'follow#follows'
    resources :follow, :only => [:create, :destroy]
  end

  match "split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated? # are we authenticated?
    request.env['warden'].authenticate! # authenticate if not already
    # or even check any other condition
    request.env['warden'].user.is_admin?
  }
  get "messages/compose", :to => "messages#compose"
  post "messages/deliver", :to => "messages#deliver", :as => :message_deliver
  put "messages/update", :to => "messages#update", :as => :messages_update
  get "messages/autosuggest", :to => "messages#autosuggest"
  get "messages/markasread/:id", :to => "messages#markasread", :as => "markasread"
  
  resources :messages, :only => [:show, :destroy, :index]

  namespace :admin do
    resources :review, :only => [:decline, :approve, :edit, :index, :show, :update] do
      post 'decline', :on => :member
      post 'approve', :on => :member
      get 'edit', :on => :member
      put 'edit', :on => :member
    end

    resources :usermanagement, :only => [:index] do
      get 'index', :on => :member
    end

    resources :users, :only => [:edit, :update, :destroy, :new, :create]
  end

  resources :comment

  namespace :supervisor do
    resources :review 
  end

  get "query", :to => "search#query"
  get "search", :to => "search#index"

  get "static/index"
  get "aboutus", :to => "static#aboutus"
  get "team", :to => "static#team"
  get "createchallenge", :to => "static#createchallenge"
  get "challengeguidelines", :to => "static#challengeguidelines"
  get "universities", :to => "static#universities"
  get "companies", :to => "static#companies"
  get "termsofservice", :to => "static#termsofservice"
  get "privacy", :to => "static#privacy"
  get "press", :to => "static#press"

  get "dashboard", :to => "dashboard#index"

  root :to => 'static#index'

end

app/views/shared/_activities.html.haml
%ul
  - activities = Activity.where(:user_id => current_user.follows).order('created_at DESC').limit(7)
  - unless activities.empty?
    - activities.each do |activity|
      %li
        = link_to activity.user.firstname, profile_user_path(activity.user)
        - if activity.event.blank?
          = t(activity.description).html_safe
        - else
          = t(activity.description, :event => activity.event.decorate.activity_text).html_safe
        %small= "&mdash; ".html_safe + time_ago_in_words(activity.created_at) + " ago"
  - else
    %em No activity

app/views/shared/_challenge.html.haml
.challenge_detail
  %h2#title= @challenge.title
  - if @challenge.supervisor.present?
    %p.supervisor
      %i.icon-user
      %strong Supervised by
      = link_to @challenge.supervisor.fullname, profile_user_path(@challenge.supervisor)
  - if @challenge.running?
    .alert.alert-success
      This challenge has begun!

  %ul.nav.nav-tabs
    %li.active
      %a{href: "#"} Info

  .row
    .description#description.span8
      .video
        = image_tag @challenge.image.url
      %p.lead
        = @challenge.lead
      = sanitized_markdown(@challenge.description)
    .details.span4.well
      - if @challenge.supervisor == current_user
        %p.detail
          -if @challenge.draft? || @challenge.declined?
            = link_to 'Edit', edit_challenge_path(@challenge), :class => 'btn'
          -else
            = link_to 'Edit', "#", :class => 'btn disabled'
          %a{:class => "btn btn-primary", :onClick => "composeMessage('challenge', #{@challenge.id})"}
            Mail Participants
          - unless @challenge.approved? || @challenge.pending?
            %br
            = form_for @challenge, :url => @url, :html => {:multipart => true, :class => "challenge-form form-horizontal"}  do |f|
              = f.submit submit_resubmit_name(@challenge), :class => "btn btn-primary", :confirm => "You are submitting your challenge for review, continue?"
          -if @challenge.pending?
            %br
            %br
            %a{:class => "btn btn-danger", :href => revoke_challenge_path(@challenge)}
              Revoke challenge
        %hr
      - elsif current_user.is_admin?
        = link_to 'Edit', edit_challenge_path(@challenge), :class => 'btn'
        - if @challenge.approved? 
          %a{:class => "btn btn-danger", :href => revoke_challenge_path(@challenge)}
            Revoke challenge
        %hr
      - if current_user.participating_challenges.include?(@challenge)
        %p.detail
          %a{:class => "btn btn-primary", :onClick => "composeMessage('user', #{@challenge.supervisor.id})"}
            Contact Supervisor
        %hr
      %p.detail
        %i.icon-group
        %strong#participants_count
          = @challenge.participants.count
        %span.type= pluralize(@challenge.participants.count, "Participant").split.last
      %p.detail
        %i.icon-time
        %strong#commitment
          = @challenge.commitment
        %span.type Hours/week
      %p.detail
        %i.icon-calendar
        %strong#day_of_week
          = @challenge.day_of_week
        %span.type
          = @challenge.from_till
      %p.detail
        %i.icon-exclamation
        %strong#meeting_time
          = @challenge.meetingtime.strftime("%H:%M")
        %span.type
          Meetings every
          = @challenge.day_of_week
      %p.detail#location
        %i.icon-map-marker
        %strong= @challenge.location
      //------------------------------------------------------
      %hr
      .action
        = render :partial => "shared/enroll_button", :locals => {:challenge => @challenge}
      %hr
      //------------------------------------------------------
      - if @challenge.supervisor.present?
        .supervisor_detail
          %h3 About the supervisor:
          = render :partial => "profile/profile_tile", :object => @challenge.supervisor, :as => :user
        %hr
      //------------------------------------------------------
      .participants_detail
        %h3 Participants:
        = render :partial => "profile/profile_small_tile", :collection => @challenge.participants.decorate, :as => :user

app/views/shared/_challenges_list.html.haml
- list_id ||= nil
.challenges-list.row{id: list_id}
  = render challenges, :options => (options ||= {})
- if challenges.blank?
  %p No challenges to show.

app/views/shared/_enroll_button.html.haml
- if challenge.current_user_enrolled?
  - if challenge.can_unenroll?
    %a.enroll.btn.btn-primary.btn-large{:href => unenroll_challenge_path(challenge)}
      %i.icon-remove-sign
      Unenroll
  - else
    .enroll.btn.btn-succes.disabled.btn-large You're participating
- else
  - if challenge.can_enroll?
    %a.enroll.btn.btn-success.btn-large{:href => enroll_challenge_path(challenge)}
      %i.icon-ok-sign
      Enroll
  - else
    .enroll.btn.btn-succes.disabled.btn-large Enrollment has closed

app/views/shared/_form.html.haml
= form_for @challenge, :url => @url, :html => {:multipart => true, :class => "challenge-form form-horizontal"}  do |f|
  - r1 = !@challenge.nil? && !@challenge.start_date.nil?
  - r2 = !@challenge.nil? && !@challenge.end_date.nil?
  %br/
  .row
    .span10.offset1
      - if @challenge.errors.any?
        #error_explanation.alert.alert-error
          %a.close{"data-dismiss" => "alert"} ×
          %p
            = pluralize(@challenge.errors.count, "error")
            prohibited this challenge from being saved:
          %ul
            - @challenge.errors.full_messages.each do |msg|
              %li= msg
      .control-group
        = f.label :title , "Name:", :class => "control-label"
        .controls
          = f.text_field :title, :class => "span4 enable-popover", :placeholder => "Challenge name", "data-toggle" => "popover", "data-placement" => "right", "data-trigger" => "focus", "data-content" => "Names should be short and to the point", :title => "Challenge name"
      .control-group
        = f.label :lead , "Pitch your challenge:", :class => "control-label"
        .controls
          = f.text_area :lead, :class => "span4  enable-popover", :rows => "3", :placeholder => "Challenge lead...", "data-toggle" => "popover", "data-placement" => "right", "data-trigger" => "focus", "data-content" => "Why should people join your challenge? Keep it short and make it exciting! (120 characters max.)", :title => "Pitch your challenge"
      .control-group
        = f.label :image , "Challenge Image:", :class => "control-label"
        .controls
          - if @challenge.image.present?
            = image_tag @challenge.image.thumb.url, :class => "img-rounded"
          = f.hidden_field :image_cache
          = f.file_field :image, :title => "<i class='icon-cloud-upload' /> Select an image"
      .control-group
        = f.label :description , "Description:", :class => "control-label"
        .controls
          = f.text_area :description, :class => "span8 enable-popover", :rows => "10", :placeholder => "Description...", "data-toggle" => "popover", "data-placement" => "left", "data-trigger" => "focus", "data-content" => "Basic formatting with markdown: \n Use _text_ for italic, use **text** for bold. Make lists via '* listitem' and '1.  listitem'. \nLinks are automatically parsed, you can also name them with [GitHub](http://github.com)", :title => "Description"
      .control-group
        = f.label :start_date , "Dates:", :class => "control-label"
        .controls
          - if r1
            = f.text_field :start_date, :value => @challenge.start_date.strftime("%d-%m-%Y")
          - else
            = f.text_field :start_date
          till
          - if r2
            = f.text_field :end_date, :value => @challenge.end_date.strftime("%d-%m-%Y")
          - else
            = f.text_field :end_date
      .control-group
        = f.label :meetingtime, "Meeting time:", :class => "control-label"
        .controls
          = f.time_select :meetingtime
          %br
          %small
            Meetings are held every week, starting on the first day of the challenge
      .control-group
        = f.label :location , "Location:", :class => "control-label"
        .controls
          = f.text_field :location, :placeholder => "Challenge location... ", :class => "enable-popover", "data-toggle" => "popover", "data-placement" => "right", "data-trigger" => "focus", "data-content" => "This can be a roomnumber, office or something else. (Leave blank if undecided)", :title => "Challenge location"
      .control-group
        = f.label :commitment , "Commitment", :class => "control-label"
        .controls
          = f.text_field :commitment, :placeholder => "Challenge commitment... ", :class => "enable-popover", "data-toggle" => "popover", "data-placement" => "right", "data-trigger" => "focus", "data-content" => "What is the minimal number of hours per week a student should commit to this challenge?", :title => "Challenge Commitment"
      .control-group
        .controls
          -if current_user.is_admin?
            = f.submit "Save challenge", :class => "btn btn-primary", :confirm => "You are using sudo magic, continue?"
          -else
            = f.submit 'Save draft', :class => "btn"
            = f.submit submit_resubmit_name(@challenge), :class => "btn btn-primary", :confirm => "You are submitting your challenge for review, continue?"