config/routes.rb
Challengesplatform::Application.routes.draw do
  match '/challenges/page/:page' => "challenges#index"
  match '/challenges/:filter/(page/:page)' => "challenges#index", :constraints => { :filter => /upcoming|running|past|enrolled|supervising/ }

  resources :challenges, :constraints => { :id => /[0-9]+/ } do
    get 'revoke', :on => :member
    get 'enroll', :on => :member
    get 'unenroll', :on => :member
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  }

  resources :users, :except => [:index, :create] do
    get 'profile', :on => :member, :to => "profile#show"
    get 'followers' => 'follow#followers'
    get 'follows' => 'follow#follows'
    resources :follow, :only => [:create, :destroy]
  end

  match "split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated? # are we authenticated?
    request.env['warden'].authenticate! # authenticate if not already
    # or even check any other condition
    request.env['warden'].user.is_admin?
  }
  get "messages/compose", :to => "messages#compose"
  post "messages/deliver", :to => "messages#deliver", :as => :message_deliver
  put "messages/update", :to => "messages#update", :as => :messages_update
  get "messages/autosuggest", :to => "messages#autosuggest"
  get "messages/markasread/:id", :to => "messages#markasread", :as => "markasread"
  
  resources :messages, :only => [:show, :destroy, :index]

  namespace :admin do
    resources :review, :only => [:decline, :approve, :edit, :index, :show, :update] do
      post 'decline', :on => :member
      post 'approve', :on => :member
      get 'edit', :on => :member
      put 'edit', :on => :member
    end

    resources :usermanagement, :only => [:index] do
      get 'index', :on => :member
    end

    resources :users, :only => [:edit, :update, :destroy, :new, :create]
  end

  resources :comment

  namespace :supervisor do
    resources :review 
  end

  get "query", :to => "search#query"
  get "search", :to => "search#index"

  get "static/index"
  get "aboutus", :to => "static#aboutus"
  get "team", :to => "static#team"
  get "createchallenge", :to => "static#createchallenge"
  get "challengeguidelines", :to => "static#challengeguidelines"
  get "universities", :to => "static#universities"
  get "companies", :to => "static#companies"
  get "termsofservice", :to => "static#termsofservice"
  get "privacy", :to => "static#privacy"
  get "press", :to => "static#press"

  get "dashboard", :to => "dashboard#index"

  root :to => 'static#index'

end

app/controllers/admin/usermanagement_controller.rb
class Admin::UsermanagementController < Admin::AdminController
  def index
    # Get an overview of the users
    @users = User.decorate
    render :index
  end
end

app/views/admin/usermanagement/_usermanagementtablerow.html.haml
%tr
  %td.id= user.id
  %td.firstname= link_to user.firstname, profile_user_path(user)
  %td.lastname= user.lastname
  %td.email= user.email
  %td.role= (['student', 'supervisor', 'admin'])[user.role]
  %td.state= user.active ? "active" : "disabled"
  %td.last_login
    =user.last_sign_in_at.strftime("%d-%m-%Y") unless user.last_sign_in_at.nil?
    ="N/A" if user.last_sign_in_at.nil?
  %td.actions
    -if user.id.eql? current_user.id or user.id.eql? 1
      %a{:class => "btn disabled", :title => "message is disabled"}
        %i.icon-envelope
      -if user.id.eql? current_user.id
        %a{:class => "btn", :title => "edit #{user.firstname}", :href => edit_user_registration_path }
          %i.icon-pencil
      -else
        %a{:class => "btn disabled", :title => "edit disabled"}
          %i.icon-pencil
      %a{:class => "btn disabled", :title => "delete is disabled"}
        %i.icon-trash.color-pomegranate
    -else
      %a{:class => "btn", :title => "message #{user.firstname}", :onClick => "composeMessage('user', #{user.id})"}
        %i.icon-envelope
      %a{:class => "btn", :title => "edit #{user.firstname}", :href => edit_admin_user_path(user) }
        %i.icon-pencil
      %a{:class => "btn", :title => "delete #{user.firstname}", :href => admin_user_path(user), :data => {:method => :delete, :confirm => "Are you sure you want to remove user \"#{user.firstname}\" from the system?" }}
        %i.icon-trash.color-pomegranate

app/views/admin/usermanagement/index.html.haml
%input{:type => :hidden, :id =>'page_identifier', :value => 'admin/usermanagement.index'}
%h2
  User management

%p.pull-right
  %a{:class => "btn btn-primary", :title => "Create user", :href => new_admin_user_path}
    %i.icon-plus-sign
    Add user

%div#user-list
  %div.input-prepend
    %span.add-on
      %i.icon-search
    %input.search{:type => "text", :placeholder => "Search"}

  %table.table
    %thead
      %tr
        %th.sort{:data_sort => "id"} ID
        %th.sort{:data_sort => "firstname"} Firstname
        %th.sort{:data_sort => "lastname"} Lastname
        %th.sort{:data_sort => "email"} Email
        %th.sort{:data_sort => "role"} Role
        %th.sort{:data_sort => "state"} State
        %th.sort{:data_sort => "last_login"} Last login
        %th Actions
    %tbody.list
      - @users.each do |user|
        = render :partial => 'admin/usermanagement/usermanagementtablerow', :object => user, :as => 'user'

%p.pull-right
  %a{:class => "btn btn-primary", :title => "Create user", :href => new_admin_user_path}
    %i.icon-plus-sign
    Add user